version: '2'
services:
  solr:
    build: .
    expose:
      - "8983"
    ports:
      - "8983:8983"
    environment:
      SERVER_HOST: "0.0.0.0"
    volumes:
      - tlre-solr-data:/usr/share/elasticsearch/data
volumes:
  tlre-solr-data:
    driver: local
